// Code generated by Kitex v0.7.1. DO NOT EDIT.

package login

import (
	api "SimpleDouyin/user/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return loginServiceInfo
}

var loginServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Login"
	handlerType := (*api.Login)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo":  kitex.NewMethodInfo(echoHandler, newLoginEchoArgs, newLoginEchoResult, false),
		"login": kitex.NewMethodInfo(loginHandler, newLoginLoginArgs, newLoginLoginResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "api",
		"ServiceFilePath": "user.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.LoginEchoArgs)
	realResult := result.(*api.LoginEchoResult)
	success, err := handler.(api.Login).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLoginEchoArgs() interface{} {
	return api.NewLoginEchoArgs()
}

func newLoginEchoResult() interface{} {
	return api.NewLoginEchoResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.LoginLoginArgs)
	realResult := result.(*api.LoginLoginResult)
	success, err := handler.(api.Login).Login(ctx, realArg.Lreq)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLoginLoginArgs() interface{} {
	return api.NewLoginLoginArgs()
}

func newLoginLoginResult() interface{} {
	return api.NewLoginLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.LoginEchoArgs
	_args.Req = req
	var _result api.LoginEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, lreq *api.LoginRequest) (r *api.LoginResponse, err error) {
	var _args api.LoginLoginArgs
	_args.Lreq = lreq
	var _result api.LoginLoginResult
	if err = p.c.Call(ctx, "login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
